import { Task, TaskStatus, Project } from './types';

// Sample projects data
export const sampleProjects: Project[] = [
  {
    id: '1',
    name: 'Website Redesign',
    description: 'Redesigning the company website with modern UI/UX',
    color: '#FF5733',
    tasksCount: 2,
    createdAt: new Date('2024-01-01').toISOString(),
    updatedAt: new Date('2024-01-01').toISOString(),
  },
  {
    id: '2',
    name: 'Mobile App Development',
    description: 'Building a new mobile app for task management',
    color: '#33FF57',
    tasksCount: 2,
    createdAt: new Date('2024-01-01').toISOString(),
    updatedAt: new Date('2024-01-01').toISOString(),
  },
  {
    id: '3',
    name: 'Marketing Campaign',
    description: 'Q1 2024 digital marketing campaign',
    color: '#3357FF',
    tasksCount: 1,
    createdAt: new Date('2024-01-01').toISOString(),
    updatedAt: new Date('2024-01-01').toISOString(),
  },
];

// Sample tasks data with all required fields
export const sampleTasks: Task[] = [
  {
    id: '1',
    title: 'Design new dashboard layout',
    description: 'Create wireframes and mockups for the new admin dashboard layout',
    status: TaskStatus.TODO,
    priority: 'high',
    projectId: '1',
    createdAt: new Date('2024-01-01').toISOString(),
    updatedAt: new Date('2024-01-01').toISOString(),
    dueDate: new Date('2024-02-01').toISOString(),
  },
  {
    id: '2',
    title: 'Implement authentication system',
    description: 'Set up user authentication with NextAuth.js',
    status: TaskStatus.IN_PROGRESS,
    priority: 'high',
    projectId: '2',
    createdAt: new Date('2024-01-02').toISOString(),
    updatedAt: new Date('2024-01-02').toISOString(),
    dueDate: new Date('2024-02-15').toISOString(),
  },
  {
    id: '3',
    title: 'Create content calendar',
    description: 'Plan and organize content for social media posts',
    status: TaskStatus.TODO,
    priority: 'medium',
    projectId: '3',
    createdAt: new Date('2024-01-03').toISOString(),
    updatedAt: new Date('2024-01-03').toISOString(),
    dueDate: new Date('2024-02-28').toISOString(),
  },
  {
    id: '4',
    title: 'Optimize database queries',
    description: 'Improve performance of main dashboard queries',
    status: TaskStatus.DONE,
    priority: 'medium',
    projectId: '2',
    createdAt: new Date('2024-01-04').toISOString(),
    updatedAt: new Date('2024-01-04').toISOString(),
    dueDate: new Date('2024-01-20').toISOString(),
  },
  {
    id: '5',
    title: 'Write API documentation',
    description: 'Document all API endpoints and their usage',
    status: TaskStatus.IN_PROGRESS,
    priority: 'low',
    projectId: '1',
    createdAt: new Date('2024-01-05').toISOString(),
    updatedAt: new Date('2024-01-05').toISOString(),
    dueDate: new Date('2024-02-10').toISOString(),
  },
]; 